[project]
name = "cams-biometrics-mcp" 
version = "0.1.0"
dependencies = [
    "fastmcp>=0.1.0",
    "httpx>=0.25.0"
    # Add other dependencies your cams_biometrics.py needs
]

[project.scripts]
start = "cams_biometrics:main"  # Points to your main function